### ISSUE TITLE
Cannot declare class because the name is already in use

### ISSUE THREAD

**Issue by samyak45** [goaop/framework#374] opened 2017-12-08 15:16 UTC
Following the tutorial, as it is, for a project I am working on gave **'class not found exception'** in:
1. configuring the ApplicationAspectKernel in the front controller, 
2. registering aspect in aspect kernel, and 
3.  declaring pointcut in an aspect for the methods of some class

To solve this, I **added include statements**:
1. include '../application/ApplicationAspectKernel.php'; for my project's front controller
2. include 'aspect/MonitorAspect.php'; in ApplicationAspectController.php
3. include  '../application/controller/CallbackController.php'; in MonitorAspect.php (CallbackController is the class whose methods I want to intercept).

On doing this I get the error **PHP Fatal error:  Cannot declare class CallbackController, because the name is already in use in /var/www/html/vyom-crm-frontend/application/controller/CallbackController.php on line 0**

[Edit]: I removed the third include above. This resolved the above error. Now, the interceptor didn't work with the following pointcut 

`@Before("execution(public CallbackController->*(*))")`

This pointcut works - `@Before("execution(public **->*(*))")
`
But I don't want to intercept all methods of all classes. There is a specific method in CallbackController that I want to intercept.

Please help me solve this. Thanks!

**Comment by TheCelavi** [comment] 2017-12-08 16:47
It seams that you are not using Composer (https://getcomposer.org) for auto loading classes?

In order for Go! AOP to work properly, usage of Composer as class autoloader is u must.

**Comment by samyak45** [comment] 2017-12-08 21:33
@TheCelavi I am using Composer. Code in my index.php -


```
<?php


// Auto-loading the classes (currently only from application/libs) via Composer's PSR-4 autoloader
// Later it might be useful to use a namespace here, but for now let's keep it as simple as possible
require '../vendor/autoload.php';

include_once '../application/ApplicationAspectKernel.php';

if(class_exists('ApplicationAspectKernel')) {
// Initialize an application aspect container
    $applicationAspectKernel = ApplicationAspectKernel::getInstance();
    $applicationAspectKernel->init(array(
        'debug' => true, // use 'false' for production mode
        // Cache directory
        'cacheDir' => null,
        // Include paths restricts the directories where aspects should be applied, or empty for all source files
        'includePaths' => array(
            __DIR__.'/../application/'
        )
    ));
}
else {
    error_log("class ApplicationAspectKernel not found");
}

// Start our application
new Application();

?>
```

**Comment by lisachenko** [comment] 2017-12-08 21:41
Hi, your init section looks invalid. Where is your `appDir` setting? And you should always configure the `cacheDir` option in order to have good performance.

You should also remove first include for `ApplicationAspectKernel.php` and additional check for class existence.

Could you also show the namespace of your `CallbackController`? And please, report your version of framework too.

**Comment by samyak45** [comment] 2017-12-09 12:46
@lisachenko 
your init section looks invalid. Where is your appDir setting - Couldn't follow what you mean. Which part are you calling the 'init section' and which settings are appDir settings?

You should also remove first include for ApplicationAspectKernel.php and additional check for class existence. - that gives class not found exceptions.

Could you also show the namespace of your CallbackController - It has no declared namespace.

report your version of framework  - ^2.1

**Comment by TheCelavi** [comment] 2017-12-09 19:02
`appDir` - (sorry, not documented setting, will be fixed with new documentation) a path which points to a rood folder of your project/application source. `includePaths` is optional and should point to additional directories where your source code residue (or at least, code which should be weaved.). If you are familiar with Symfony - you may see Go! AOP Symfony bundle for reference.

> You should also remove first include for ApplicationAspectKernel.php and additional check for class existence. - that gives class not found exceptions.

If you are getting "class not found" exception when loading your class - that means that Composer is not all setup properly to load your classes. 

In general, if Composer is setup properly (and you are using Composer for class autoloading) - beside "require '../vendor/autoload.php';" you should not have any need to use `require`, `include` and so on... for class loading in your project, except, of course, in your app entry script (e.g. index.php)

If you are getting "Cannot declare class CallbackController, because the name is already in use" that simply means what it said - CallbackController is being loaded twice. It is going to be hard to give you any more info if there is no full insight in application code (at least for me, maybe Alexandar would have more luck).

**Comment by samyak45** [comment] 2017-12-09 20:15
@TheCelavi  parts of the application code that might be helpful -
**index.php**
```
<?php

require '../vendor/autoload.php';

$applicationAspectKernel = ApplicationAspectKernel::getInstance();
$applicationAspectKernel->init(array(
    'debug' => true, // use 'false' for production mode
    // Cache directory
    'appDir' => '../application/',
    'cacheDir' => null,
    // Include paths restricts the directories where aspects should be applied, or empty for all source files
    'includePaths' => array(
        '../application/'
    )
));
// Start our application
new Application();
```
**composer.json**
```
{
    "name": "Inventory",
    "type": "project",
    "description": "Inventory",
    "keywords": ["mvc"],
    "homepage": "https://rightklick.in/",
    "license": "MIT",
    "require-dev": {
        "php": ">=5.5.0"
    },
    "autoload": {
        "psr-4": { "": ["application/core/", "application/model/"] }
    },
    "require": {
        "goaop/framework": "^2.1"
    }
}
```
**autoload.php**

```
<?php

// autoload.php @generated by Composer

require_once __DIR__ . '/composer/autoload_real.php';

return ComposerAutoloaderInit4dad9c0cc8cbc9a8baecb2ef83f1193c::getLoader();
```
**autoload_real.php**
```
<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit4dad9c0cc8cbc9a8baecb2ef83f1193c
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit4dad9c0cc8cbc9a8baecb2ef83f1193c', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader();
        spl_autoload_unregister(array('ComposerAutoloaderInit4dad9c0cc8cbc9a8baecb2ef83f1193c', 'loadClassLoader'));

        $useStaticLoader = PHP_VERSION_ID >= 50600 && !defined('HHVM_VERSION') && (!function_exists('zend_loader_file_encoded') || !zend_loader_file_encoded());
        if ($useStaticLoader) {
            require_once __DIR__ . '/autoload_static.php';

            call_user_func(\Composer\Autoload\ComposerStaticInit4dad9c0cc8cbc9a8baecb2ef83f1193c::getInitializer($loader));
        } else {
            $map = require __DIR__ . '/autoload_namespaces.php';
            foreach ($map as $namespace => $path) {
                $loader->set($namespace, $path);
            }

            $map = require __DIR__ . '/autoload_psr4.php';
            foreach ($map as $namespace => $path) {
                $loader->setPsr4($namespace, $path);
            }

            $classMap = require __DIR__ . '/autoload_classmap.php';
            if ($classMap) {
                $loader->addClassMap($classMap);
            }
        }

        $loader->register(true);

        if ($useStaticLoader) {
            $includeFiles = Composer\Autoload\ComposerStaticInit4dad9c0cc8cbc9a8baecb2ef83f1193c::$files;
        } else {
            $includeFiles = require __DIR__ . '/autoload_files.php';
        }
        foreach ($includeFiles as $fileIdentifier => $file) {
            composerRequire4dad9c0cc8cbc9a8baecb2ef83f1193c($fileIdentifier, $file);
        }

        return $loader;
    }
}

function composerRequire4dad9c0cc8cbc9a8baecb2ef83f1193c($fileIdentifier, $file)
{
    if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
        require $file;

        $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;
    }
}
```

**Comment by samyak45** [comment] 2017-12-11 07:51
@TheCelavi @lisachenko does the above part of the application code help understanding what am I doing wrong?

**Comment by lisachenko** [comment] 2017-12-11 09:26
Hi, only missing option is `cacheDir` right now, strange that it still works for you, because there should be an exception. All other settings look ok...

**Comment by samyak45** [comment] 2017-12-11 10:03
@lisachenko  but I am still not being able to define pointCut specific for the class/method I want to intercept.

This works - `@Before("execution(public **->*(*))")`
This doesn't - `@Before("execution(public CallbackController->*(*))")`

**Comment by samyak45** [comment] 2017-12-11 10:08
@lisachenko I am still having to use `include_once '../application/ApplicationAspectKernel.php';` without it the error `PHP Fatal error:  Uncaught Error: Class 'ApplicationAspectKernel' not found`  still comes.

**Comment by lisachenko** [comment] 2017-12-11 10:17
> I am still having to use include_once '../application/ApplicationAspectKernel.php';

This is because your configuration for PSR-4 is incorrect:
```
    "autoload": {
        "psr-4": { "": ["application/core/", "application/model/"] }
    },
```
Please, add `"application/"` directory to this list or move this `ApplicationAspectKernel.php` file into your `core` directory, so composer will be able to find it.

**Comment by lisachenko** [comment] 2017-12-11 10:19
> This doesn't - @Before("execution(public CallbackController->*(*))")

Please, give me full path and content of this `CallbackController` file (without method bodies), including the namespaces, uses, includes, etc. And several methods (only names, without bodies).

**Comment by samyak45** [comment] 2017-12-11 10:55
class not found errors resolved. For the pointcut part:

> give me full path and content of this CallbackController file (without method bodies), including the namespaces, uses, includes, etc. And several methods (only names, without bodies).

full path - <project_folder>/application/controller/CallbackController.php

namespace - none (no namespaces have been used in the controllers and models of this project)

includes - none

extends - Controller

methods - foo() (there is only one method apart from the constructor.)

**Comment by lisachenko** [comment] 2017-12-11 14:02
> PHP Fatal error: Uncaught Error: Class 'aspect\\MonitorAspect' not found

It's the same, you have not configured autoload section in your composer.json file. Just move to `application/core` directory or adjust your composer.json file. Also, remove `aspect` namespace in this file - you should either configure autoloader or clean it if you move it into the `application/core` directory. After that aspect will be registered and AOP should apply to your files.

From what I can see, all troubles in this issue are because of wrong composer configuration/autoloading initialization.

**Comment by samyak45** [comment] 2017-12-11 14:08
@lisachenko the class not found errors were resolved. (As I said in my previous comment). The pointcut issue remains.

**Comment by samyak45** [comment] 2017-12-11 14:17
To attempt to solve the pointcut issue I, -

1. Added namespace `controller\callback` to CallbackController.php.
2. Since CallbackController extends Controller, added namespace core\controller to Controller.php containing the parent class Controller, and added `use \core\controller\Controller;` to CallbackController.php
3. Added a `use controller\callback;` statement to MonitorAspect.php

This gave new errors: PHP Fatal error:  Class 'Controller' not found. (Class Controller is in application/core should be auto included.

@lisachenko my composer autoload settings now are - 
```
"autoload": {
        "psr-4": { "": ["application/core/", "application/model/", "application/controller/", "application/aspect/"] }
    },
```
Also I have successfully run composer update after changing conposer.json (this is what resolved class not found on MonitorAspect).

**Comment by lisachenko** [comment] 2017-12-11 15:17
@samyak45 Please, resolve all class "xxx" not found errors before asking about help, as I'm sure that it's simple incorrect configuration of composer. If you have troubles in configuring composer loader, then I would recommend you not to use AOP for a while, because knowing PSR-0,4 standards is must have.

To debug all class XXX not found, just create new instances of them right after include of  autoload file.
```
require '../vendor/autoload.php';
```
You should be able to create instance of aspect kernel, aspect instance, your controller instance.
After that we can check why it's not working for you.

**Comment by samyak45** [comment] 2017-12-12 07:12
@lisachenko is using namespaces necessary to use goaop?
This works without having to use namespaces in my project `@Before("execution(public **->*(*))")`
But `@Before("execution(public CallbackController->*(*))")` doesn't work for functions inside controller. (Though it does work for the constructors of controller classes.)

Also, I am being able to intercept methods of CallbackModel used by CallbackController using `@Before("execution(public CallbackModel::*(*))")`. However, I want to intercept at controller level.

**Comment by lisachenko** [comment] 2017-12-12 15:50
> @lisachenko is using namespaces necessary to use goaop?

No it isn't necessary, engine can work with global namespace too.

Just for fun, try to use `@Before("execution(public **\*Contr*->*(*))")` Who knows...
In order to find out what is the root cause you should debug why pointcut isn't matched for your class. 

You have definitely some typo somewhere: in classname or in the pointcut...

PS: I'm right that methods in your controller are not final?

**Comment by samyak45** [comment] 2017-12-13 12:41
> Just for fun, try to use @Before("execution(public **\*Contr*->*(*))") Who knows.

Doesn't work.

> You have definitely some typo somewhere: in classname or in the pointcut...

No. I have rechecked. Have also got other members of my team to review but no luck.

> I'm right that methods in your controller are not final

No. They are not.

One thing though - the controllers in my project convert to url by the logic - all controller classes must end with the string 'Controller'. When hitting any controller named <x>Controller, you don't need to put 'Controller' in the url, just '<base_url>/x/<controller_method> works.

Does above information help?

PS: `Using @Before("execution(public **->*(*))")` intercepts the controller constructor but no other methods.

**Comment by lisachenko** [comment] 2017-12-13 13:47
@samyak45 have no idea what is wrong :( Description of your issue is pretty simple, but in order to check what is wrong, I need to debug it right on your instance.

I have tried to reproduce you case:
1. `composer create-project goaop/framework`
2. Created `demos/controller` directory and put `CallbackController.php` file with following content:

```php
<?php

class CallbackController
{
    public function testHello()
    {
        echo "yay!";
    }
}
```
3. In the `autoload_aspect.php` file I've added
```php
$controller = new CallbackController();
$controller->testHello();
```
4. Changed `LoggingAspect` pointcut to the `@Before("execution(public CallbackController->*(*))")` (I'm using Go! AOP Framework plugin with PhpStorm, so I can see A⬇️  icon in the gutter)
5. Added into `composer.json` section for loading my controller from `demos/controller` directory:
```
        "psr-4": {
            "": "demos/controller/"
         }
```
6. Warmed composer (in order to generate autoload files)
7. Refreshed my page - and everything works:
```
Calling Before Interceptor for execution(CallbackController->testHello()) with arguments: []
yay!
```

**Comment by lisachenko** [comment] 2017-12-17 19:34
@samyak45 Is there any progress?

**Comment by samyak45** [comment] 2017-12-20 07:15
@lisachenko no I couldn't solve it so to get my work done for now I added a new function to my CallbackModel, that now does all that happened in CallbackController function I wanted to intercept. And I added interceptor for this function in the model. Architecturally this isn't right but was compelled to use this hack to get work done. 

Thanks. You can now close this issue.

**Comment by lisachenko** [comment] 2017-12-20 09:08
Ok, wish you good luck. 

Ping me if some help will be required.

**Closed as completed by lisachenko** 2017-12-20 09:08 UTC
Labels: Support
