### ISSUE TITLE
Execution + multiple !within in pointcut expression is not working

### ISSUE THREAD

**Issue by andreyvk** [goaop/framework#218] opened 2015-04-15 06:03 UTC
Hi,

I have the following expression:

```
/**
 * @Before("execution(public **\controllers\*Controller->handle_*(*)) && !within(**\base\controllers\*Controller) && !within(**\common\controllers\LoginController)")
 */
```

It seems that only the first `within` is considered and the latter isnt working. Is that expected behavior?

**Comment by lisachenko** [comment] 2015-04-15 12:37
~~This maybe related to the #217~~

~~Is `LoginController` class extends a class that matches `**\controllers\*Controller`?~~

**Comment by lisachenko** [comment] 2015-04-15 12:51
Just reproduced this issue myself, so it's definitely a bug.

**Comment by lisachenko** [comment] 2015-04-15 13:05
Parser reads this expression like this: `execution(...) && ( !(within(...) && !within(...)) )` Which has an incorrect meaning because of double negation for the last item.

Dissect parser, which is used for parsing doesn't have a priority rules for precendence, so this results in the incorrect parsing of this expression.

I'll look into this issue and try to fix it via grammar if possible.

As a quick fix - just add a brackets and put logical or like this:
`execution(...) && !(within(...) || within (...))`

**Comment by andreyvk** [comment] 2015-04-15 15:03
That works, thank you. Should've thought of that myself. Will wait for the bug to get fixed :)

**Comment by lisachenko** [comment] 2015-04-24 10:10
Hi! Here is some information about this issue.

I have spent several evenings in the researching of the way how to fix that bug. What I discovered is the fact that LALR parser which is used in dissect can't handle such pointcut grammar correctly. This is a sad fact, because I need either to replace parser with LR one (which is more complex and memory inefficient) or just patch this library for supporting precedence of concrete rules.

I hope, that this weekend will be free for me and I will be able to improve some things in the framework for upcoming 1.0 version.

**Comment by andreyvk** [comment] 2015-04-25 12:44
I think efficiency is the key, so patching is a better choice.

Just wanna ask: you have some sort of precedence in annotation processing, right? Say, in this particular case, it looks like `execution` has to be processed first and then `within`'s must be applied on top of that. Is that correct?

**Comment by lisachenko** [comment] 2015-04-25 13:39
Yes, the issue is in my grammar, it was defined incorrectly and this was lead to the described issue. I want to say thank to @fduch for helping me with grammar, he suggested me the working solution and I'm now ready to fix that issue ) 

I need some cleaning of code, but if you are interested in grammar definition, here is a working one: https://gist.github.com/lisachenko/e2ccdfd89ddd03882fb2

Pay an attention to the lines 39-65, it's a working solution for LALR grammar. Shame for me that I wasn't able to define it clearly from the beginning.

**Comment by fduch** [comment] 2015-04-26 12:43
@lisachenko :+1:  )

**Comment by lisachenko** [comment] 2015-04-29 19:05
Fixed by #220

**Closed as completed by lisachenko** 2015-04-29 19:05 UTC
Labels: Pointcut, Bug

**Comment by andreyvk** [comment] 2015-04-30 09:17
Wow, great news! :+1:

**Comment by lisachenko** [comment] 2015-04-30 09:21
@andreyvk This is only the first part, there should be one more for correct handling of complex expressions during matching. Current behavior is incorrect and I want to fix this in nearest time. 

But grammar now is much reliable and stable ) I hope not to receive any new issues with it

**Comment by andreyvk** [comment] 2015-04-30 10:49
That's good to know! Any time estimates on release of  v1.0? )

**Comment by lisachenko** [comment] 2015-04-30 13:19
There is no concrete estimate for v1.0 now, it depends on many factors (mainly my free time and inspiration). 
There are few things that I want to put into v1.0: solid code coverage (about 80% or higher), php-parser as source analyzer instead of outdated TokenReflection, support for PHP5.6 with variadics and special composer type handler for aspects installation.

**Comment by andreyvk** [comment] 2015-05-01 06:47
Seems like a it's going to be a long time before the release. Any chance you release with a minimal set of enhancements first and then build upon it, adding more and releasing subsequent minor versions?
