### ISSUE TITLE
Parser in PHP 7.4 fails (even without using new PHP features)

### ISSUE THREAD

**Issue by l00k** [goaop/framework#426] opened 2019-08-09 17:46 UTC
Not sure if it is related to framework itself or rather to php-parser dependency.
~~If initialization feature is enabled on PHP 7.4 (beta2) parser fails with error similar to:~~
```
Uncaught ParseError: syntax error, unexpected end of file, expecting '('
```
~~It is in line where `new Object()` is placed.~~
~~On previous PHP versions it works ok, also if I disable initialization feature.~~

**EDIT**
I have found out that it is related to `SourceTransformingLoader::filter()`
it looks like transformed code is stiped to source code length - that is why it prints unexpected end of file.
It is because `new Klass()` is replaced with `\Go\Instrument\Transformer\ConstructorExecutionTransformer::getInstance()->{Klass::class}()`
and `include_once AOP_CACHE_DIR . '/_proxies/app/(...)` is appended to end of file

It looks like `php_user_filter` has changed a little in 7.4. It accepts characters limited to inital data size?

**Comment by l00k** [comment] 2019-08-11 21:07
That is something with `filter` method or `include`.
Check that sample code. I have tested it on PHP 7.3 (works well) and on PHP 7.4beta2 and I get error:
`Parse error: syntax error, unexpected end of file in /(...)/Sample.php on line 9`

```
// index.php

include __DIR__ . '/SampleFilter.php';
SampleFilter::register();

$uri = 'php://filter/read=sample.filter/resource='. __DIR__ . '/Sample.php';

$content = file_get_contents($uri);

include $uri;
Sample::printIt();
```

```
// SampleFilter.php

class SampleFilter extends php_user_filter
{
    public const PHP_FILTER_READ = 'php://filter/read=';
    public const FILTER_IDENTIFIER = 'sample.filter';
    
    protected $data = '';
    protected static $filterId;
    
    public static function register(string $filterId = self::FILTER_IDENTIFIER) : void
    {
        if (!empty(self::$filterId)) 
        {
            throw new RuntimeException('Stream filter already registered');
        }
        
        $result = stream_filter_register($filterId, __CLASS__);
        if ($result === false)
        {
            throw new Exception('Stream filter was not registered');
        }
        
        self::$filterId = $filterId;
    }
    
    public static function getId() : string
    {
        if (empty(self::$filterId))
        {
            throw new Exception('Stream filter was not registered');
        }
        
        return self::$filterId;
    }
    
    public function filter($in, $out, &$consumed, $closing)
    {
        while ($bucket = stream_bucket_make_writeable($in))
        {
            $this->data .= $bucket->data;
        }
        
        if ($closing || feof($this->stream))
        {
            $consumed = strlen($this->data);
            
            echo '<h2>Before</h2><pre>'. htmlentities($this->data) .'</pre>';
            $this->data = str_replace('text', 'text!!!!!!!!', $this->data);
            echo '<h2>After</h2><pre>'. htmlentities($this->data) .'</pre>';
            
            $bucket = stream_bucket_new($this->stream, $this->data);
            stream_bucket_append($out, $bucket);
            
            return PSFS_PASS_ON;
        }
        
        return PSFS_FEED_ME;
    }
    
}
```

```
// Sample.php

class Sample
{

    public static function printIt()
    {
        echo 'text';
    }

}
```

I will also ask on SO - maybe someone would know what happened to filters in PHP 7.4.

**Comment by lisachenko** [comment] 2019-08-12 16:46
Yes, this is definitely a bug in the **php-7.4.0beta1** when including file with enabled stream filter, in previous versions everything is ok.

**Comment by lisachenko** [comment] 2019-08-12 17:04
Reported a bug: https://bugs.php.net/bug.php?id=78406

**Comment by lisachenko** [comment] 2019-08-13 08:28
This bug was fixed in https://github.com/php/php-src/commit/2e4f76dc803d46a64cfa52bc70b4158ed0cc4992 by @nikic.

Thank you for reporting and @nikic for quick fixing!

**Closed as completed by lisachenko** 2019-08-13 08:28 UTC
Labels: Bug

**Comment by fjzubi** [comment] 2020-08-12 17:53
Hi, trying to make it work in my project with php 7.0.33, I'm having the following issue, line `include_once AOP_CACHE_DIR . '/_proxies/controller/instance/Instance.php/controller/instance/Instance.php';` is inserted in the middle of a cached class (almost the end and then it fails. 

Snippet code: 

```
private function getFilter(array $requestBody): qa_DaoFilter {
        $filterA = new qa_DaoFilter();
        $value = getValueOrDefaultForKey('user', $requestBody,null);
        $filterA->setUser
include_once AOP_CACHE_DIR . '/_proxies/controller/instance/Instance.php/controller/instance/Instance.php';($value);
        return $filterA;
}
```
Reported error: 

`phpLog: PHP Parse error:  syntax error, unexpected 'include_once' (T_INCLUDE_ONCE)`

**Comment by lisachenko** [comment] 2020-08-12 17:57
@fjzubi try to downgrade to goaop version 2.3.2 to see if it's working. Probably, something is wrong now in newest version.

**Comment by fjzubi** [comment] 2020-08-12 18:25
Hi, thanks for the answer, but didn't work. :( 
Same issue, I write here the composer.json of the POC I'm working on (trying to integrate it with Slim fwk), may be a dependency conflict is the cause 
``` {
  "require": {
    "monolog/monolog": "^1.25",
    "slim/slim": "3.*",
    "tuupola/slim-jwt-auth": "2.*",
    "goaop/framework": "2.3.2"
  },
  "autoload": {
    "psr-4": {
      "controller\\": "controller",
      "routes\\": "apirest\\routes",
      "middleware\\": "middleware",
      "aop\\": "apirest\\aop"
    }
  }
}    
```

**Comment by fjzubi** [comment] 2020-08-13 15:13
Hi, I even tried the Demo example, and same result :( 

`PHP Parse error:  syntax error, unexpected 'include_once' (T_INCLUDE_ONCE), expecting ',' or ')' in /home/sb3/www/pocAop/demos/Demo/Example/LoggingDemo.php:57`

```
{    
    "require": {        
        "goaop/framework": "2.3.2"
    },
    "autoload": {
      "psr-4": {
        "Demo\\": "Demo"
      }
    }
}
```
It's a pity. 
Thanks anyway.

**Comment by lisachenko** [comment] 2020-08-13 20:47
Hi, @fjzubi, there is an issue with general `nikic/php-parser` library. Downgrade it to < 4.7.0

**Comment by fjzubi** [comment] 2020-08-13 21:06
Excellent!!! It works!! Many thanks @lisachenko
