### ISSUE TITLE
[Support] AOP is not applied to the static method called with self:: keyword

### ISSUE THREAD

**Issue by dulio** [goaop/framework#348] opened 2017-08-18 14:47 UTC
main code:
```
class TestService {
    public static function testOne($a, $b) {
        return self::testTwo($a , $b);
    }

    /**
     * @Cacheable(ttl=60)
     */
    public static function testTwo($a, $b) {
        return $a + $b;
    }
}
```

call code:
`$res = TestService::testOne(11, 4);`

I found that: the second called static function not work with AOP
but the first static function works well.

go aop version: 2.1.2

**Comment by TheCelavi** [comment] 2017-08-18 14:56
We can not see the issue here, you have to provide us with full example, how did you imported Cacheable annotation and how Aspect looks like - there are too few details here to even grasp what is wrong. Beside that, what is the expected result and how did you came to conclusion that function is not woven?

**Comment by lisachenko** [comment] 2017-08-18 14:59
I know, what the root cause here.

In order to use AOP with static methods, you should use `static` keyword in methods body to enable Late Static Binding (aka LSB)

So, change 
```php
return self::testTwo($a , $b);
```
to the
```php
return static::testTwo($a , $b);
```

**Comment by TheCelavi** [comment] 2017-08-18 15:00
@lisachenko Wow, that is quite important info! Will add it do documentation as well.

**Comment by dulio** [comment] 2017-08-18 15:02
I got it, thx!

**Comment by lisachenko** [comment] 2017-08-18 15:03
@dulio You are welcome! Thank you for using the framework!

**Comment by TheCelavi** [comment] 2017-08-18 18:38
After some thinking -> this is a bug, not framework limitation. We can fix this.  Consider this:

    class A {
        static function x() {    
        }

        static function y() { 
            self::x();
        }
    }

if we weave class A on function x, we will get:

    class A_AopProxied {
        static function x() {    
        }

        static function y() { 
            self::x();
        }
    }

    class A {
        private static $__joinPoints = []

        static function x() {    
            return self::$__joinPoints['static:x']->__invoke($this);
        }
    }

and that is why `static` has to be used - **unless!!!** when we generate `A_AopProxied` do simple string replacement where `self::` is replaced with `A::` then we will get:

    class A_AopProxied {
        static function x() {    
        }

        static function y() { 
            A::x();
        }
    }

    class A {
        private static $__joinPoints = []

        static function x() {    
            return self::$__joinPoints['static:x']->__invoke($this);
        }
    }

and there will be no need for late static binding. Right?

**Comment by TheCelavi** [comment] 2017-08-18 18:40
Two reason why I propose this:
- Framework should not force change in coding, if `self` is intended to be used, we should not force users to change it to `static` -> we can brake their code if there are more levels of inheritance and different semantics where `static` could jeopardize that logic
- Late static binding is slower, no need to introduce it where we can avoid it.

Agree?

**Comment by lisachenko** [comment] 2017-08-18 22:56
Ha! ) It was my first attempt many years ago to replace class name for the `self` keyword. In short: your solution won't work because of scope rules. Let me show this:

First example with private static property:

```php
class A__AopProxied {
    private static $instance;
    public static function getInstance() {
        // ... logic
        return self::$instance; // <== If in this place you change self to static or to "A", you will get fatal
    }
}

class A extends A__AopProxied {
}
```

See: https://3v4l.org/8AS2C

The same issue will be with calling private static methods from public or protected scope.

Another issue: it's almost impossible to correctly handle LSB by invoking additional advices and make it working with scopes correctly (and recursion!). All my previous attempts were unsuccessful, so current implementation is the MOST advanced working solution.

So there are 3 issues:
  - private scope of static methods/properties. Access should be performed only in parent scope otherwise you will get fatal error.
  - preservation of LSB during calling of parent methods and additional advices.
  - prevent recursion for calling overridden/parent static methods in the framework (it can quickly run out of control)

Maybe you will find solution for those issues? )

But from my knowledge and experience it's impossible to do this correctly in all other ways. So, changing `self` to `static` is my small price for using interception of static methods. No one modern test frameworks can not handle static methods like GoAOP. 

Better to close this issue to prevent summoning unicorns... 😆

**Comment by lisachenko** [comment] 2017-08-18 23:08
Linked to #94

**Comment by lisachenko** [comment] 2017-08-18 23:09
Duplicates #130

**Comment by TheCelavi** [comment] 2017-08-19 07:43
Ok, you got several valid points there. Agree.

**Closed as completed by TheCelavi** 2017-08-19 07:43 UTC
Labels: Known Issue, Support

**Comment by lisachenko** [comment] 2018-01-05 19:49
@TheCelavi it's now implemented on AST-level. `self` keyword is only preserved for accessing static properties because without that fatal error will be generated.
